config/routes.rb
Rails.application.routes.draw do
  resources :sources
  root to: 'welcome#index'
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_one :source
  has_many :units
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/engine.rb
class Engine

  def initialize
    @pool = Concurrent::FixedThreadPool.new(5) # 5 threads
  end

  def turn
    Account.find_each do |a|
      sandbox = Sandbox::Base.new(account: a)
      @pool.post do
        sandbox.run
        logic   = sandbox.namespace::Logic.new
        account = Sanitizer.new()
        units   = State::Units.new
        game    = Game.new(account, units)
        logic.turn(game)
      end
    end
  end

end

app/models/game.rb
class Game
    # State methods
    def account
      [:balance, :materials]
    end

    def units
      []
    end

    # Action methods
    def create
    end

    def destroy
    end

    def edit
    end

    def move
    end

    def stop
    end

    def scan
    end

    def attack
    end

  end
end

app/models/game/account.rb
class Game::Account < ApplicationRecord
  belongs_to :user
  has_many :units, class_name: 'Game::Unit'
end

app/models/game/state.rb
class Game::State

  def initialize(user:)
    @account = user.account
  end

  def account
    Sandbox::Account.new(@account)
  end

  def units
    @account.units.map(&:id)
  end
end

app/models/game/unit/spaceship.rb
class Game::Unit::Spaceship < Game::Unit

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user
end

app/models/sandbox/base.rb
module Sandbox
  class Base

    def initialize(account:)
      @account = account
      @sandbox ||= Shikashi::Sandbox.new("::Sandbox_#{@account.id}")
    end

    def privileges
      @privileges ||= Sandbox::Privileges.new
    end

    def turn
      @run   ||= run
      @units ||= Sandbox::Unit.new(@account).alive
      logic.turn(state: Sandbox::State.new(@account, units).to_json)
    end

    def run
      @sandbox.run(privileges.turn, @account.source.code)
      true
    end

    def namespace
      @sandbox.base_namespace
    end

  end # class
end # module

app/models/sandbox/privileges.rb
module Sandbox
  class Privileges
    def turn
      privileges = Shikashi::Privileges.new
      privileges.allow_method :to_s
      privileges.allow_class_definitions
      privileges.instances_of(Class).allow :new
      privileges.instances_of(Integer).allow_all
      privileges.instances_of(OpenStruct).allow_all

      privileges.allow_const_read 'Game'
      privileges.instances_of(Game::State).allow_all
      privileges.instances_of(Game::Account).allow(:balance)
      privileges.instances_of(Game::Unit).allow(:id)
    end
  end
end

app/models/sandbox/state.rb
module Sandbox
  class State
    def initialize(account:)
      @account = account
    end

    def turn
      {
        balance: @account.balance,
        units: Units.new(@account).alive
      }
    end
  end
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  code       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Source < ApplicationRecord
  belongs_to :account

  def run(sandbox:)
    sandbox.run(code)
  end

end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sources
  has_many :messages
  has_one :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to sources_path, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:code).merge({user_id: current_user.id})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_if(section, action = nil)
    if match_controller(section, action)
      { class: 'active' }
    else
      { class: 'inactive' }
    end
  end

  def simple_form_horizontal(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(html: { class: "form-horizontal #{object}" }, wrapper: :horizontal_form)), &block)
  end

  protected
  def match_controller(section, action)
    (section == controller_path) and (action.nil? or action == action_name)
  end

  # def match_namespace(section)
  #   section == controller.class.parent.name.downcase
  # end

end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  - if message.is_a?(String)
    .alert.alert-dismissible{class: "alert-#{ type.to_sym == :notice ? 'info' : 'success' }" }
      %button.close{ data: { dismiss: "alert" } }
        %span{:'aria-hidden' => true} &times;
        %span.sr-only Close
      = message
  - elsif message.is_a?(ActiveModel::Errors)
    .alert.alert-dismissible.alert-danger
      %button.close{ data: { dismiss: "alert" } }
        %span{:'aria-hidden' => true} &times;
        %span.sr-only Close
      - message.full_messages.each do |msg|
        %p= msg

app/views/layouts/_navbar.html.haml
.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to content_for?(:title) ? yield(:title) : (ENV['APP_TITLE'] || Rails.application.class.parent_name), root_path, class: "navbar-brand"

  %button.navbar-toggler(type="button" data-toggle="collapse" data-target="#NavMain" aria-controls="NavMain" aria-expanded="false" aria-label="Toggle navigation")
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#NavMain
    - if user_signed_in?
      %ul.navbar-nav.flex-grow-1
        %li{ active_if('sources') }
          = link_to t('menu.sources', default: 'Sources'),  sources_path, class: 'nav-link'
        %li{ active_if('test', 'index') }
          = link_to t('menu.inactive', default: 'Inactive'),  root_path, class: 'nav-link'
      %ul.navbar-nav
        %li.nav-item
          .navbar-text v:0.1.0
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle#navbarDropdown(href='#' role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false")
            #{current_user.email}
          .dropdown-menu(aria-labelledby="navbarDropdown")
            = link_to t('menu.logout', default: 'Logout'),  destroy_user_session_path, method: :delete, class: 'dropdown-item'
    - else
      %ul.navbar-nav.flex-grow-1
        %li.nav-item
      %ul.navbar-nav
        %li.nav-item
          .navbar-text v:0.1.0
        %li{ active_if('devise/sessions') }
          = link_to t('menu.login', default: 'Login'),  new_user_session_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %title= content_for?(:title) ? yield(:title) : (ENV['APP_TITLE'] || Rails.application.class.parent_name)
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible'}
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}
    %link{rel: "stylesheet", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css", integrity: "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB", crossorigin: "anonymous"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag controller_path, media: 'all', 'data-turbolinks-track' => true
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js", integrity: "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", crossorigin: "anonymous", 'data-turbolinks-track': 'reload'}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js", integrity: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", crossorigin: "anonymous", 'data-turbolinks-track': 'reload'}
    %script{src: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js", integrity: "sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T", crossorigin: "anonymous", 'data-turbolinks-track': 'reload'}
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag controller_path, 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
    = yield :head
  %body
    .container-fluid
      = render 'layouts/navbar'
    = yield :header
    .container
      = render 'layouts/messages'
    .container
      - if controller.class.parent == Devise
        = yield
      - else
        = render template: 'layouts/fie'
    = yield :footer

app/views/sources/_form.html.haml
-# frozen_string_literal: true

-# = simple_form_for(@source, remote: true, format: :json) do |f|

= simple_form_for(@source) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.hidden_field :code
    #editor= @source.code


  .form-actions
    = f.button :submit, class: 'btn btn-primary', id: 'submit'
    = link_to 'Cancel', sources_path, class: 'btn btn-secondary'

- console if Rails.env.development?

app/views/sources/edit.html.haml
%h1
  Listing sources

= render 'form'

app/views/sources/index.html.haml
%h1
  Listing sources
  %small
    = link_to 'new', new_source_path

- @sources.each do |source|
  .row
    .col-md-12
      %pre
        = source.code
  .row
    .col-md-12
      = link_to 'Edit', edit_source_path(source)
      = link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' }

- console if Rails.env.development?

app/views/sources/new.html.haml
%h1 New source

= render 'form'

app/views/sources/show.html.haml
%p#notice= notice

%p
  %b User:
  = @source.user
%p
  %b Code:
  = @source.code

= link_to 'Edit', edit_source_path(@source)
\|
= link_to 'Back', sources_path

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml